default_agent: document_processor
agents:
  document_processor:
    name: document_processor
    entrypoint: C:/Users/mohanaj/git/ent-agentic-platform/agents/document_processor/document_processor.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: C:\Users\mohanaj\git\ent-agentic-platform\agents\document_processor
    aws:
      execution_role: arn:aws:iam::843074507558:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-8349e2633a
      execution_role_auto_create: false
      account: '843074507558'
      region: us-east-1
      ecr_repository: 843074507558.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-document_processor
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: document_processor-zmJ8bz636b
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:843074507558:runtime/document_processor-zmJ8bz636b
      agent_session_id: 73376dec-58a9-4b8d-97e4-8825a10406a2
    codebuild:
      project_name: bedrock-agentcore-document_processor-builder
      execution_role: arn:aws:iam::843074507558:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-8349e2633a
      source_bucket: bedrock-agentcore-codebuild-sources-843074507558-us-east-1
    memory:
      mode: STM_AND_LTM
      memory_id: document_processor_mem-dlH9yzCkW7
      memory_arn: null
      memory_name: document_processor_memory
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
